version: "3.6"
services:
  postgres:
    container_name: database
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /data/postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: always
